"""Create users and sessions table

Revision ID: d24c4bbda652
Revises: 
Create Date: 2020-10-18 20:56:47.965754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24c4bbda652'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'token', 'created_at')
    )
    op.execute('''
    CREATE FUNCTION create_session(user_id integer, token varchar) RETURNS integer AS $$
    BEGIN
        DELETE FROM sessions WHERE user_id = $1;
        INSERT INTO sessions (user_id, token) VALUES ($1, $2) RETURNING id;
        RETURN id;
    END;
    $$ LANGUAGE plpgsql;
    ''')
    op.execute('''
        CREATE FUNCTION delete_user(user_id integer) RETURNS null AS $$
        BEGIN
            DELETE FROM sessions WHERE user_id = $1;
            DELETE FROM users WHERE user_id = $1
        END;
        $$ LANGUAGE plpgsql;
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
