"""poitns and routes tables

Revision ID: 383c9697117a
Revises: 
Create Date: 2020-10-30 16:48:17.696986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383c9697117a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['meta'], ['routes_meta.id'], ),
    sa.ForeignKeyConstraint(['point'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('routes_meta')
    op.drop_table('points')
    # ### end Alembic commands ###
