"""points and routes

Revision ID: cff0918bfbb0
Revises: 
Create Date: 2020-10-31 10:54:09.289018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff0918bfbb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_points_id', 'points', ['id'], unique=False)
    op.create_table('routes_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_routes_meta_id', 'routes_meta', ['id'], unique=False)
    op.create_index('idx_routes_meta_id_name', 'routes_meta', ['id', 'name'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('meta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meta'], ['routes_meta.id'], ),
    sa.ForeignKeyConstraint(['point'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_meta_field', 'routes', ['meta'], unique=False)
    op.create_index('idx_routes_meta_point', 'routes', ['meta', 'point'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_routes_meta_point', table_name='routes')
    op.drop_index('idx_routes_meta_field', table_name='routes')
    op.drop_table('routes')
    op.drop_index('idx_routes_meta_id_name', table_name='routes_meta')
    op.drop_index('idx_routes_meta_id', table_name='routes_meta')
    op.drop_table('routes_meta')
    op.drop_index('idx_points_id', table_name='points')
    op.drop_table('points')
    # ### end Alembic commands ###
